/**: 
  controller_manager:
    ros__parameters:
      update_rate: 1000  # Hz

      moveit_arm_controller:
        type: joint_trajectory_controller/JointTrajectoryController

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      franka_robot_state_broadcaster:
        type: franka_robot_state_broadcaster/FrankaRobotStateBroadcaster
      
      cartesian_motion_controller:
        type: cartesian_motion_controller/CartesianMotionController

      joint_impedance_example_controller:
        type: franka_example_controllers/JointImpedanceExampleController

      robotiq_gripper_controller:
        type: position_controllers/GripperActionController

      robotiq_activation_controller:
        type: robotiq_controllers/RobotiqActivationController


/**:
  franka_robot_state_broadcaster:
    ros__parameters:
      lock_try_count: 5 # Number of attempts to acquire the lock in a single on_update()
      lock_sleep_interval: 5 # microseconds sleep between attempts
      lock_log_error: false #  Log error if lock acquisition fails - false == do not log  
      lock_update_success: true # return update OK, although lock fails (no update occurs)
      
/**: 
  moveit_arm_controller:
    ros__parameters:
      command_interfaces:
        - effort #REAL
        #- position #SIM
      state_interfaces:
        - position
        - velocity
      joints:
        - fr3_joint1
        - fr3_joint2
        - fr3_joint3
        - fr3_joint4
        - fr3_joint5
        - fr3_joint6
        - fr3_joint7
      gains:
        fr3_joint1: { p: 600., d: 30., i: 0., i_clamp: 1. }
        fr3_joint2: { p: 600., d: 30., i: 0., i_clamp: 1. }
        fr3_joint3: { p: 600., d: 30., i: 0., i_clamp: 1. }
        fr3_joint4: { p: 600., d: 30., i: 0., i_clamp: 1. }
        fr3_joint5: { p: 250., d: 10., i: 0., i_clamp: 1. }
        fr3_joint6: { p: 150., d: 10., i: 0., i_clamp: 1. }
        fr3_joint7: { p: 50., d: 5., i: 0., i_clamp: 1. }

/**: 
  cartesian_motion_controller:
    ros__parameters:

      # See the cartesian_compliance_controller
      end_effector_link: "fr3_link8"
      robot_base_link: "fr3_link0"
      joints:
        - fr3_joint1
        - fr3_joint2
        - fr3_joint3
        - fr3_joint4
        - fr3_joint5
        - fr3_joint6
        - fr3_joint7

      # See the cartesian_compliance_controller
      command_interfaces:
        - position
        #- velocity

      solver:
          error_scale: 1.0
          iterations: 10
          publish_state_feedback: True

      pd_gains:
          trans_x: {p: 1.0}
          trans_y: {p: 1.0}
          trans_z: {p: 1.0}
          rot_x: {p: 0.5}
          rot_y: {p: 0.5}
          rot_z: {p: 0.5}

/**:
  joint_impedance_example_controller:
    ros__parameters:
      k_gains:
        - 24.0
        - 24.0
        - 24.0
        - 24.0
        - 10.0
        - 6.0
        - 2.0
      d_gains:
        - 2.0
        - 2.0
        - 2.0
        - 1.0
        - 1.0
        - 1.0
        - 0.5

/**:
  robotiq_gripper_controller:
    ros__parameters:
      default: true
      joint: robotiq_85_left_knuckle_joint
      use_effort_interface: true
      use_speed_interface: true

/**:
  robotiq_activation_controller:
    ros__parameters:
      default: true