# This is a namespace agnostic configuration file for the Franka FR3 robot.
# That is to say, it is not tied to any specific namespace and can be used in
# any namespace. 
# If you require namespace specific configurations, you can easily modify this
# file to include the namespace
# As an example, below you can find:
#
# /**:
#   franka_robot_state_broadcaster:
#     ros__parameters:
#       lock_try_count: 5
#       lock_sleep_interval: 5
#
# Imagine, you have a specific need to have the lock try count in namespace "NAMESPACE_X"
# to be different than the default value of 5, but leave all the other namespaces as default.
# Add the following lines to the configuration file 
# (or use a different config file, but then you have to mody the launch script to reference that file)
#
# /NAMESPACE_X:
#   franka_robot_state_broadcaster:
#     ros__parameters:
#       lock_try_count: 10
#       lock_sleep_interval: 35
# /**:
#   franka_robot_state_broadcaster:
#     ros__parameters:
#       lock_try_count: 5
#       lock_sleep_interval: 5


/NS_1:
  controller_manager:
    ros__parameters:
      update_rate: 1000
      thread_priority: 98

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      left_cartesian_motion_controller:
        type: cartesian_motion_controller/CartesianMotionController

/NS_1:
  left_cartesian_motion_controller:
    ros__parameters:

      # See the cartesian_compliance_controller
      end_effector_link: "left_fr3_link8"
      robot_base_link: "left_fr3_link0"
      joints:
        - left_fr3_joint1
        - left_fr3_joint2
        - left_fr3_joint3
        - left_fr3_joint4
        - left_fr3_joint5
        - left_fr3_joint6
        - left_fr3_joint7

      # See the cartesian_compliance_controller
      command_interfaces:
          #- position
        - velocity
      
      solver:
        error_scale: 1.0
        iterations: 10
        publish_state_feedback: True

      pd_gains:
          trans_x: {p: 1.0}
          trans_y: {p: 1.0}
          trans_z: {p: 1.0}
          rot_x: {p: 0.5}
          rot_y: {p: 0.5}
          rot_z: {p: 0.5}

/NS_1:
  joint_state_broadcaster:
    ros__parameters:
      arm_id: "fr3"
      joints:
        - left_fr3_joint1
        - left_fr3_joint2
        - left_fr3_joint3
        - left_fr3_joint4
        - left_fr3_joint5
        - left_fr3_joint6
        - left_fr3_joint7