controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    left_robotiq_gripper_controller:
      type: position_controllers/GripperActionController
    
    right_robotiq_gripper_controller:
      type: position_controllers/GripperActionController

    left_cartesian_motion_controller:
      type: cartesian_motion_controller/CartesianMotionController

    right_cartesian_motion_controller:
      type: cartesian_motion_controller/CartesianMotionController

    left_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


left_cartesian_motion_controller:
  ros__parameters:

    # See the cartesian_compliance_controller
    end_effector_link: "left_fr3_link8"
    robot_base_link: "left_fr3_link0"
    joints:
      - left_fr3_joint1
      - left_fr3_joint2
      - left_fr3_joint3
      - left_fr3_joint4
      - left_fr3_joint5
      - left_fr3_joint6
      - left_fr3_joint7

    # See the cartesian_compliance_controller
    command_interfaces:
        #- position
      - velocity

    solver:
        error_scale: 1.0
        iterations: 10
        publish_state_feedback: True

    pd_gains:
        trans_x: {p: 1.0}
        trans_y: {p: 1.0}
        trans_z: {p: 1.0}
        rot_x: {p: 0.5}
        rot_y: {p: 0.5}
        rot_z: {p: 0.5}

right_cartesian_motion_controller:
  ros__parameters:

    # See the cartesian_compliance_controller
    end_effector_link: "right_fr3_link8"
    robot_base_link: "right_fr3_link0"
    joints:
      - right_fr3_joint1
      - right_fr3_joint2
      - right_fr3_joint3
      - right_fr3_joint4
      - right_fr3_joint5
      - right_fr3_joint6
      - right_fr3_joint7

    # See the cartesian_compliance_controller
    command_interfaces:
        #- position
      - velocity

    solver:
        error_scale: 1.0
        iterations: 10
        publish_state_feedback: True

    pd_gains:
        trans_x: {p: 1.0}
        trans_y: {p: 1.0}
        trans_z: {p: 1.0}
        rot_x: {p: 0.5}
        rot_y: {p: 0.5}
        rot_z: {p: 0.5}
        
left_robotiq_gripper_controller:
  ros__parameters:
    default: true
    joint: left_robotiq_85_left_knuckle_joint
    use_effort_interface: true
    use_speed_interface: true

right_robotiq_gripper_controller:
  ros__parameters:
    default: true
    joint: right_robotiq_85_left_knuckle_joint
    use_effort_interface: true
    use_speed_interface: true

joint_state_broadcaster:
    ros__parameters:
      arm_id: "fr3"
      joints:
        - left_fr3_joint1
        - left_fr3_joint2
        - left_fr3_joint3
        - left_fr3_joint4
        - left_fr3_joint5
        - left_fr3_joint6
        - left_fr3_joint7
        - right_fr3_joint1
        - right_fr3_joint2
        - right_fr3_joint3
        - right_fr3_joint4
        - right_fr3_joint5
        - right_fr3_joint6
        - right_fr3_joint7
        - left_robotiq_85_left_knuckle_joint
        - right_robotiq_85_left_knuckle_joint

left_joint_trajectory_controller:
  ros__parameters:
    joints:
      - left_fr3_joint1
      - left_fr3_joint2
      - left_fr3_joint3
      - left_fr3_joint4
      - left_fr3_joint5
      - left_fr3_joint6
      - left_fr3_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

right_joint_trajectory_controller:
  ros__parameters:
    joints:
      - right_fr3_joint1
      - right_fr3_joint2
      - right_fr3_joint3
      - right_fr3_joint4
      - right_fr3_joint5
      - right_fr3_joint6
      - right_fr3_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity